spring:
  application:
    name: insights-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource: 
    url: ${SPRING_DATASOURCE_URL:jdbc:clickhouse://localhost:8123/clickhouse}}
    username: ${SPRING_DATASOURCE_USERNAME:${CLICKHOUSE_USER:clickhouse}}
    password: ${SPRING_DATASOURCE_PASSWORD:${CLICKHOUSE_PASSWORD:clickhouse}}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

  sql:
    init:
      mode: always

server:
  port: 8084
