version: '3.8'

services:
  postgres-plaid:
    image: postgres:15
    container_name: postgres-plaid
    env_file:
      - config/.postgres-plaid-adapter
    ports:
      - "${POSTGRES_PLAID_PORT}:5432"
    volumes:
      - postgres-plaid-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-keycloak:                              
    image: postgres:15
    container_name: postgres-keycloak
    env_file:
      - config/.postgres-keycloak
    ports:
      - "${POSTGRES_KEYCLOAK_PORT}:5432"
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped  

                     

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command: start-dev
    env_file:
      - config/.keycloak
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    restart: unless-stopped
                    

  plaid-adapter-service:
    build:
      context: ./plaid-adapter-service
      dockerfile: Dockerfile
    container_name: plaid-adapter-service
    env_file:
      - config/.plaid-adapter
    ports:
      - "${PLAID_SERVICE_PORT}:8084"
    depends_on:
      postgres-plaid:
        condition: service_healthy
    volumes:
      - maven-repo:/root/.m2
      - ./plaid-adapter-service/src:/app/src
      - ./plaid-adapter-service/pom.xml:/app/pom.xml


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    env_file:
      - config/.api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8085"
    volumes:
      - maven-repo:/root/.m2
      - ./api-gateway/src:/app/src
      - ./api-gateway/pom.xml:/app/pom.xml   

volumes:
  postgres-plaid-data:
  postgres-keycloak-data:
  maven-repo:
  api-gateway: