graph TD
    provider["Financial Data Provider Adapter"] -->|account.observed.v1| rabbit["RabbitMQ"]
    rabbit --> account["Account Service"]
    account -->|account.recorded.v1| rabbit
    rabbit --> insightsAccounts["Insights Service"]

    provider -->|transaction.observed.v1| rabbit
    rabbit --> transaction["Transaction Service"]
    transaction -->|transaction.recorded.v1| rabbit
    rabbit --> insightsTransactions["Insights Service"]
    rabbit --> budgeting["Budgeting Service"]
