spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: jsonplaceholder-route
          uri: https://jsonplaceholder.typicode.com
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        - id: account-service-route
          uri: ${ACCOUNT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1


        - id: plaid-adapter-service-route
          uri: ${PLAID_ADAPTER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/keycloak-realm/protocol/openid-connect/certs

server:
  port: ${API_GATEWAY_PORT:8085}
