version: '3.8'

services:
  postgres-plaid:
    image: postgres:15
    container_name: postgres-plaid
    env_file:
      - ./.env.plaid-adapter
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-plaid-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  plaid-adapter-service:
    build:
      context: ../plaid-adapter-service
      dockerfile: Dockerfile
    container_name: plaid-adapter-service
    env_file:
      - ./.env.plaid-adapter
    ports:
      - "${PLAID_SERVICE_PORT}:8084"
    depends_on:
      postgres-plaid:
        condition: service_healthy
    volumes:
      - maven-repo:/root/.m2
      - ./../plaid-adapter-service/src:/app/src
      - ./../plaid-adapter-service/pom.xml:/app/pom.xml

volumes:
  postgres-plaid-data:
  maven-repo: