global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8085"]
        labels:
          application: api-gateway

  - job_name: account-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["account-service:8083"]
        labels:
          application: account-service

  - job_name: transaction-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["transaction-service:8086"]
        labels:
          application: transaction-service

  - job_name: plaid-adapter-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["plaid-adapter-service:8082"]
        labels:
          application: plaid-adapter-service

  - job_name: consent-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["consent-service:8092"]
        labels:
          application: consent-service

  - job_name: insights-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["insights-service:8084"]
        labels:
          application: insights-service

  - job_name: budgeting-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["budgeting-service:8089"]
        labels:
          application: budgeting

  - job_name: dashboard-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["dashboard-service:8090"]
        labels:
          application: dashboard-service

  - job_name: ai-assistant-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ai-assistant-service:8091"]
        labels:
          application: ai-assistant
