server:
  port: ${SAGA_ORCHESTRATION_PORT:8087}

spring:
  application:
    name: saga-orchestration

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
    template:
      retry:
        enabled: true
        initial-interval: 2s

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5437/saga_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE