spring:
  application:
    name: plaid-adapter-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/plaid_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        observation-enabled: true
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 3
    template:
      observation-enabled: true
      retry:
        enabled: true
        initial-interval: 2s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL:http://localhost:8080}/realms/keycloak-realm
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8080}/realms/keycloak-realm/protocol/openid-connect/certs

  cloud:
    openfeign:
      micrometer:
        enabled: true
      circuitbreaker:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: create

server:
  port: ${PLAID_SERVICE_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  opentelemetry:
    resource-attributes:
      deployment.environment: ${DEPLOYMENT_ENVIRONMENT:local}
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://grafana-lgtm:4318/v1/traces}
          transport: http
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_LOGS_ENDPOINT:http://grafana-lgtm:4318/v1/logs}
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://grafana-lgtm:4318/v1/metrics}

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false

plaid:
  api: ${PLAID_API_ID:68f013c09bda9e001fac9053}
  secret: ${PLAID_API_SECRET:2a1cf9a2fc0dfb5152c552709accfc}
  env: ${PLAID_ENV_TYPE:sandbox}
  webhook:
   url: ${PLAID_WEBHOOK_URL:https://71l6b2-2a0b-4140-ab40--2.ru.tuna.am/api/plaid/webhook}

accountclient:
  url: ${ACCOUNT_SERVICE_URL:http://localhost:8083}/accounts

transactionclient:
  url: ${TRANSACTION_SERVICE_URL:http://localhost:8086}/transactions
