spring:
  application:
    name: plaid-adapter-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/plaid_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  security:
    oauth2:
      client:
        registration:
          wallet-hub-internal:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${INTERNAL_CLIENT_ID:wallet-hub-internal}
            client-secret: ${INTERNAL_CLIENT_SECRET:wallet-hub-internal-secret}
        provider:
          keycloak:
            token-uri: ${INTERNAL_CLIENT_TOKEN_URL:http://localhost:8080/realms/keycloak-realm/protocol/openid-connect/token}

  jpa:
    hibernate:
      ddl-auto: validate

  cloud:
    openfeign:
      micrometer:
        enabled: true
      circuitbreaker:
        enabled: false

server:
  port: 8082

plaid:
  api: ${PLAID_API_ID:}
  secret: ${PLAID_API_SECRET:}
  env: ${PLAID_ENV_TYPE:sandbox}
  webhook:
   url: ${PLAID_WEBHOOK_URL:https://71l6b2-2a0b-4140-ab40--2.ru.tuna.am/api/plaid/webhook}

accountclient:
  url: ${ACCOUNT_SERVICE_URL:http://localhost:8083}/accounts

transactionclient:
  url: ${TRANSACTION_SERVICE_URL:http://localhost:8086}/transactions
