ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS version;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS connection_status;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS disabled_at;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS removed_at;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS sync_version;

DROP TABLE IF EXISTS transaction_registry;
DROP TABLE IF EXISTS account_registry;
DROP TABLE IF EXISTS outbox_events;
