ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS version;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS connection_status;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS disabled_at;
ALTER TABLE IF EXISTS connection DROP COLUMN IF EXISTS removed_at;
